### ISSUE TITLE
NPS prompt style is biased by showing which scores are associated with detractors/netural/promoters

### ISSUE THREAD

**Issue by solumos** [burtonator/polar-bookshelf#1040]
**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

**DONATE OR PURCHASE POLAR PREMIUM FOR PRIORITIZED SUPPORT AND FEATURES **

https://opencollective.com/polar-bookshelf

**Is your feature request related to a problem? Please describe.**
The NPS survey prompt is inherently biased. The coloration of the buttons should not denote how the score is calculated.

**Describe the solution you'd like**
Each score should be the same, neutral color. Otherwise, respondents may be biased by the coloration, influencing the data collected.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/burtonator/polar-bookshelf/blob/0e7e8c40e5cfd8afc4769d3a1b623b9125337be5/web/js/ui/feedback/Feedback.tsx#L318-L332

**Comment by burtonator** [comment]
Ah.. interesting. I actually agree 100% and realized this a couple months back. I actually think I might have wrote up a blog post about this somewhere but forget. There might be an issue on it.

I decided to keep this style for one big reason - everyone else is doing it.

The challenge here is that I wouldn't be able to compare our NPS score to other companies which I think is valuable.

IT seems everyone else is doing this style so I kind of have to stick to it.  At least for now.  I might A/B test it.

There seems to be a chasm where people don't pick 9 because they don't feel it's tipped into 'green' ... which might bias us lower.  

I think I have the data to prove that.

![image](https://user-images.githubusercontent.com/45447/59447216-bd8a4d80-8db7-11e9-94e8-c7effb3e27e6.png)

yeah.. you can see how it falls off there.

I'm goign to leave it as it is for a while and resolve it in the future.
