### ISSUE TITLE
Make sure imported files are hard linked NOT copied 

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#1323]
This improves performance and reduces disk space but not sure if we've enabled it by default yet.

**Comment by hikerito** [comment]
I think it should be a configurable option; I would certainly expect that "importing" a pdf into some pdf management software actually creates a COPY and that my original sources will be totally unaffected, and whatever I might do with the originals (for example editing, deleting pages from them, annotating in some other software, etc) isn't going to affect my reading in polar. A hard link is a totally different matter. Now if you create hardlinks instead of copying, Polar can't expect the same content each time it opens the same file; and I can't be sure that Polar won't damage my files. And they'll be locked for editing when read in polar, right? so on a lot of levels I think it's just goin to be potentially a very damaging thing to do.

**Comment by hikerito** [comment]
And what about importing from a usb drive?

**Comment by galantra** [comment]
I support this feature and would like to illustrate a use case:

I use [Zotero](https://github.com/zotero/zotero). I have many PDFs in a dedicated folder (on my HDD, not my SSD). They are _linked_ in Zotero. They are not in Polar.
When I open them in Polar, this creates a copy of the PDF. 
When I open them from Zotero in Polar (i.e., I drag the link from the Zotero window into the Polar window), this creates yet another copy of the PDF.

A more intuitive way to me is linking, like in Zotero.

**Comment by aleksejrs** [comment]
On filesystems supporting CoW (like btrfs), you can use `cp --reflink` to copy without using much more space until a copy is modified.

**Comment by burtonator** [comment]
n/a in 2.0

**Comment by galantra** [comment]
> 
> 
> n/a in 2.0

Could you please give us a short explanation? 

Right now I'm trying out Polar 2.11 beta. It looks like files are not attached but a copy is created – the essential difference to previous versions is that the copy is in a cloud and not on the local system. 
For reading, they are temporarily downloaded.
Correct?
