### ISSUE TITLE
Tags seem to work backwards...

### ISSUE THREAD

**Issue by nixsee** [burtonator/polar-bookshelf#1375]
When you select multiple tags, it works with AND logic rather than OR. If I click two separate ones, I would expect anything that has either tag to be selected/filtered - your folders seem to work this way. I can't see a possible use case for how it is right now. 

I was very excited to try Polar beacuse I'm looking for an open-source (non-Mendeley) application with a built-in reader, but this, along with slowness of opening PDF, limited columns/metadata, and inability to use my own cloud storage makes it a non-starter. I'll stick with Zotero and Calibre for now and perhaps check back in a year or two...

**Comment by burtonator** [comment]
AND vs OR has been a tough decision.  Not sure the best way to handle this honestly.  Might have a button for this... Might also have a fast UI popup for that.

Also, working on expanding metadata fields. The changes are in the backend just not in the UI yet.

We probably won't ever support custom cloud backends though just due to the complexity.  Might add encrypted stores though.  

You CAN use git sync now with the local disk version but it has to be done manually
