### ISSUE TITLE
Lost documents after upgrade

### ISSUE THREAD

**Issue by nikhilmjn** [burtonator/polar-bookshelf#1542]
I was using Polar 1 on my desktop without cloud sync. I was unaware that Polar 2.0 will be cloud only. After the automatic upgrade and signing in, I can only see the documents that were synced 9 months ago (did not sync/login since then). There were a lot of important documents whose highlights and my progress seems lost.
Please help! Can it be recovered? Won't the information still be stored somewhere on my system? Can't Polar 2.0 auto-import the desktop data?

My system: MacOS 10.15.1. Polar 2.0.53

**Comment by jaredtumiel** [comment]
Hi! I noticed your issue because I just posted a similar one! The good news is your documents are not gone forever. Go to the github repo and redownload Polar 1, and don't log in. Your library should be rebuilt from local storage. As far as I can tell this is a problem with the file size of annotations not getting synced when you convert from 1.0 to 2.0, but I'm not certain!

**Comment by nikhilmjn** [comment]
Thanks! Worked like a charm!
