### ISSUE TITLE
Captured page is empty

### ISSUE THREAD

**Issue by fonol** [burtonator/polar-bookshelf#3]
(Windows 10)
Steps to reproduce: 

open app, File -> Capture web page
insert http://www.faz.net/aktuell/  (german newspaper)

produces empty page, .phz which is about 3kb 

log file: 
[127.0.0.1-1532024565294.txt](https://github.com/burtonator/polar-bookshelf/files/2211204/127.0.0.1-1532024565294.txt)

**Comment by burtonator** [comment]
If it's that small something probably happened with the capture. Some bug probably.. 

One thing this brings up is that the capture log needs to be stored somewhere so that I can get a copy of it for bugs.

If you're adventurous you could download the source and run ./capture.sh --quit=false --profile=default URL so that you can get the dev console.

I'll look at this anyway though as it should work.
