### ISSUE TITLE
Ability to sort by number of annotations

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#302]
This will be helpful with archived documents to find the documents with the most annotations.

**Comment by burtonator** [comment]
This will depend on the ability to hide/show columns as I don't think we want to have too many columns shown by default.

**Comment by clemux** [comment]
I would like this issue to be reconsidered, since we now have the ability to hide columns, with some hidden by default.

Depending on the kind of reading I am doing, I am not currently able to use pagemarks as an indication of reading progress. For example, while doing scientific literature review, the articles I have read the most are the ones in which I have the most highlights. **When looking for some specific article, as long as #671 is not fixed, sorting by number of annotations would help me greatly.**

Pagemarks don't work for me when I'm not sure I have understood a paragraph or its relevance to my work, and I am waiting for new knowledge before marking it as read or ignored.

**Comment by burtonator** [comment]
It's already implemented. Add the annotations field by clicking the column drop down and then add the annotations field and then click the header to sort it...

**Comment by clemux** [comment]
Indeed, I missed it... that's perfect. My bad!
