### ISSUE TITLE
Validate all Polar functionality on Windows.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#37]
I'm still not sure about all of the Windows functionality. I think all the key bindings should work and that MacOS and Linux work fine but we need to install it on Windows and make sure everything works there.

**Comment by mvanrompuy** [comment]
Hi,

New user this app (on Windows), so just learning the keybindings. An old ticket, so I'm not sure if this was just forgotten about or still needed... But since I'm going through the keybindings anyway, might as well document the results here.

OS: Windows 10
Polar version: 1.0.14

List of keybindings and **results**:
- Control Alt N - create a new pagemark on the current page
  **Creates a pagemark covering the full page**
- Control Alt click - create a pagemark on the page up until the current mouse click
  **Works in both directions (making pagemark bigger or smaller accordingly). But weird things can occur if click is combined with dragging upwards into an existing pagemark (creating a double pagemark, internal error thrown, ..). If no bug report exists for this yet, I can create an issue to describe in detail what I'm seeing.**
- Control Alt E - erase the current pagemark
  **Pagemark is deleted on the current page**
- Ctrl-Alt-T - Create a text highlight
  **Works, but only if not crossing a page boundary. If text is selected across a boundary text on the first page is highlighted.**

So the key bindings all run the correct functionality, but I'm getting some strange results when trying some less standard stuff. I'll look into the open tickets to check if these were reported before.

Other things I've tried so far:
- Adding a document (via drag-and-drop)
  **Works**
- Anki sync
  **Flashcards are correctly synced and show-up in Anki**
- Tagging
  **Can add tags/filter on them**
- Adjusting and deleting pagemarks/highlights
  **Seems to work correctly**

Anything specific you would like to see tested?
