### ISSUE TITLE
Allow for customizable keyboard shortcuts

### ISSUE THREAD

**Issue by z1lc** [burtonator/polar-bookshelf#47]
I believe Unity by default maps Ctrl + Alt + T to open a Terminal window. Would be nice to be able to change the shortcut within Polar Bookshelf instead of having to change it within Ubuntu's system settings.

**Comment by krassowski** [comment]
I identified two relevant points in the code:
https://github.com/burtonator/polar-bookshelf/blob/3bd3f41a49b230cf48c0768bc894b8fbe46e608d/web/js/highlights/text/controller/TextHighlightController.ts#L91-L115
https://github.com/burtonator/polar-bookshelf/blob/8b728c5f2c5e4445431954ceb62f8d0879348e2f/web/js/KeyEvents.ts#L6-L14

One option would be to allow customization of how meta key is treated on Linux (e.g. to allow use of ctrl instead of ctrl + alt), and the other one would be to allow custmizing the actual key that is pressed (e.g. to change from "t" to "h").

@burtonator what do you think? I've seen the commit introducing settings (1f3f005113bf801b6fbe8943e4fa42cfdc0f64c6) - is it how this ferature could be implmented?

**Comment by burtonator** [comment]
Something like that yes. We could put the key bindings in settings. 

One issue is how do we represent them across all platforms.  Also, the javascript could shouldn't have to be custom for every one.

We need some way to map them to a string I think like "Alt+T"
