### ISSUE TITLE
What's the purpose of `stash` directory? And a related bug.

### ISSUE THREAD

**Issue by karlicoss** [burtonator/polar-bookshelf#619]
As far as I can tell, the `.polar/stash` directory is just for keeping the original files for cloud sync or something? Can it be optional (globally and perhaps per-file settings) if I don't wan't to make extra copies of pdfs? Polar seems to be working with stashless files happily if you run it from terminal without importing: e.g. `polar-bookshelf something.pdf`. As in, annotations and hightlights work, the file is displayed in the document repository window, you can tag, etc. I assume that's thanks to the fingerprints. There is a minor bug associated with that though, so this issue is kind of both a bug report and feature request.  

**Describe the bug**
If the pdf was opened directly without importing, clicking on it in the Document Repository view results in an error.

**To Reproduce**
1. Open a [previously unopened in Polar] pdf from terminal `polar-bookshelf something.pdf`
2. Close the viewer and go to the Document Repository view
3. Double click on the pdf you just opened
4. You will se an UI error and something like that `Error: ENOENT: no such file or directory, stat '/home/karlicos/.polar/stash/something.pdf'` in the terminal

**Expected behavior**
There are two possibilities
1. If we use stash, I guess it should copy the file to stash first
2. However, if we agree that stash is optional:
   I think the 'state.json' file should track the last absolute location of the PDF file. That way, when you double click you'd be able to view its annotations. Then, if you move/rename the file and open it in Polar again, it can match the fingerprint and update the absolute path. If you moved your file and tried to open it from 'Document Repository' view, it could show an error and suggest the user point it to the new file location.

**Additional context**
I'm using Polar 1.9.0

Tried looking for other issues regarding 'stash' first, but that's the only one I found https://github.com/burtonator/polar-bookshelf/issues/64

If we agree on something, I'd be happy to contribute and implement it! You must be pretty busy with all these issues :)

**Comment by burtonator** [comment]
Hey.. thanks for the bug report.

The file isn't actually a duplicate.  It's a hard link.  It's just a different name for the original file basically.

The 1.9.0 issue you mentioned with not copying the file to the stash was a bug that was fixed. 

Definitely try to run the latest builds.  We're always making changes.

This is copied from the FAQ to help explain it a bit more:

https://getpolarized.io/docs/frequently-asked-questions.html


Why is Polar using so much disk space?
The Polar disk repository is actually amazingly efficient in terms of disk usage however the operating system sometimes misreports the total usage.

The main culprit is our .backup directories which are used when performing cloud syncs. We generally keep one per day for every initial sync (though we might keep more in the future).

These contain a full backup/snapshot of your disk repository at the time it was created (once per day).

However, these use what are called ‘hard links’ where we ‘link’ the same files together and they appear in two places on the filesystem but they’re actually the same file.

If you have 10 hard links to 1 file, and you count the bytes used, some tools report 10x the actual space.

However, we’re actually using very little more than the original file size sync the data is actually the same.

They’re basically just alternative for the same underlying file.

Why can’t I open files directly?
Polar has somewhat strict data requirements for the files it’s managing. The goal of Polar is to keep your data for as long as it’s valuable to you so we need to make sure it’s always consistent.

By using a dedicated data directory we can avoid accidental deletions, and mutations of files.

Additionally, since all your data is now in one place, we can support features like cloud sync, filesystem consistency checks, sharing, etc.

Some of these features aren’t implemented yet but are on the roadmap.

**Comment by burtonator** [comment]
I actually I think I misspoke and double checked. the snapshots are hard links, imports are copies.  

I'm actually going to make them hard links now.

**Comment by burtonator** [comment]
The hard links are needed for massive imports from systems like zotero so we definitely need to make this work.

**Comment by burtonator** [comment]
k.. fixed and should be in the next release.

**Comment by karlicoss** [comment]
Thanks for quick response! Wondering how would hardlinks for importing work if user's /home and the file that's imported are on different file system though (I believe it's very common).

**Comment by burtonator** [comment]
I was just implementing that as you commented actually.

for the snapshots they're always on the same file system. I revert to using a copy if the hard link creation fails.
