### ISSUE TITLE
PDFs don't seem to be loaded with range requests

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#807]
Documents how PDF.js should use range requests but it doesn't seem like these are being used AT ALL.

https://github.com/mozilla/pdf.js/issues/8422

... this might have something to do with CORS but if we can get range requests working it would be MUCH MUCH faster to support.

**Comment by burtonator** [comment]
http://www.tsgrp.com/2017/08/22/improving-viewing-performance-of-pdf-documents/

**Comment by burtonator** [comment]
I think we need to add more headers in the CORS response:

```
Add the following Headers to the Access-Control-Expose-Headers:

Accept-Ranges
Content-Range
Content-Encoding
```

**Comment by burtonator** [comment]
```
https://cloud.google.com/storage/docs/configuring-cors

If this is a preflight request, see if it includes one or more
Access-Control-Request-Header headers. If so, then ensure that each
Access-Control-Request-Header value matches a ResponseHeader value in the
bucket's CORS configuration. All headers named in the
Access-Control-Request-Header must be in the CORS configuration for the
preflight request to succeed and include CORS headers in the response.

# current headers are:
# access-control-expose-headers: Content-Length, Date, Server, Transfer-Encoding, X-GUploader-UploadID, X-Google-Trace
```

**Comment by burtonator** [comment]
This is configured via:

```
polar-bookshelf-secrets/google-storage
```

**Comment by burtonator** [comment]
doesn't seem to be working for firefox either.

**Comment by ejaz86** [comment]
@burtonator have some issue in downloading the pdf using range requests. I am using spring boot application to provide download service. viewer.html makes 1st request which is cancelled since service supports range request and initiates partial request which is as expected but there are no further requests from browser, Its just one where i am expecting it to request till whole pdf is downloaded. Is there any special header that needs to be added in response so that browser sends all request to service.

**Comment by burtonator** [comment]
@ejaz86 this isn't a Polar bug right?  This is an app your building? My advice is to look a the Polar webapp and the HTTP headers it sends ... I forget off the top of my head.  

Going to close this bug though as I don't think it's relevant anymore.
