### ISSUE TITLE
Process these new user suggestions.

### ISSUE THREAD

**Issue by burtonator** [burtonator/polar-bookshelf#840]
Batch collection fo suggestions from users that should be prioritized into features.

```

A few observations:

1. It is impossible to tell if a tag filter is active without clicking the tags dropdown.

2. There should be an 'X' to click to erase the title filter, rather than having to use backspace.

3. Maybe the title filter should also filter based on tag text?

4. The anki sync just creates new cards and leaves the old ones behind if you modify a card.

5. Tags aren't a good mechanism for the deck name. It clutters the tag namespace. You don't want tags like "title:Foo" and "author:Bar", either.

6. After using CTRL+Shift+C to make a cloze (thanks for including that, by the way), the insertion point is gone, so you have to click in the box to keep editing. This breaks a keyboard-only workflow.

7. Making clozes just counts how many times you did it since you started editing this time, so if you make two clozes and label them both c1, the next will be c3. If you then edit it and make a new cloze, you'll get another c1.

8. To use Polar for incremental reading with dozens or hundreds of documents, a scheduler will be needed. Tagging everything 'currently_reading' and sorting by oldest update works, but doing it manually isn't great.

9. Making clozes in areas dense in information leaves the text a mess of highlights. It should really be possible to have 'invisible' highlights.

10. The annotation sidebar doesn't scroll as you keep adding highlights, so it's inconvenient once you've got more than a screenful.

11. We need to be able to edit the text of highlights, or the annotation view is fully of messy, hard-to-read stuff like "If 70% com- prehension is necessary,".

12. Flashcards shouldn't show up in the annotations view--they should be filtered out by default, anyway.

13. Area highlights showing up in the annotations view isn't helpful, since there's no way to jump to the actual highlight, and they have no content.

14. Clicking the link to the doc from the annotation view should also scroll to the annotation.
Also:

15. Deleted annotations or tag modifications aren't reflected in the annotations view until polar is restarted.
MrTrvpYesterday at 8:43 PM
@5 I agree
especially because a more robust/easy to use system could be implemented
like a context menu listing all the decks already available in anki
where you can click an existing deck name
or type out something for new deck creation




16. Clicking the multi-tag button with a single doc selected should open the normal single-tagging box with the existing tags visible.

17. If the documents move around (due to e.g. sorting by Updated and updating the doc), then a doc will move 'out from under' the selection, leaving a different document selected. Instead, the selection should probably follow the document (or else be deselected).

```

**Comment by jdlongman** [comment]
+1 for Mendeley support. I recently tried to use Polar alongside Mendeley while writing a paper and it basically doubled my workload. At present Polar is simply too lacking. 

The above comment is not focusing on the core features of Mendeley, so I think it would help if I added the absolute minimum requirements for using Polar in place of Mendeley here.

1. Attributes for each file: [Author, Title, Date, [Journal, Volume, Page (for papers)], [Publisher and City (for books)], DOI.
1. Output formatted bibliography (reference list that you write at the end of a paper) based on the list of documents used in the paper. This generally takes the form "Name, Title, Journal,...". (Just look at the end of any paper to see an example).
1. This is somewhat more optional although it is a key part of the workflow - word plugin to add a reference from Polar into the document. This will show up as (Smith, 2010) or [1] depending on citation style. Then, Polar will remember what references were used in order to generate the bibliography in step 2.

**Comment by burtonator** [comment]
@jdlongman Can you advise on this related issue:

https://github.com/burtonator/polar-bookshelf/issues/841

What I'm thinking of doing is adding support for CSL-JSON which is becoming a standard alternative to bibtex.

IT's JSON so I can literally store it within the DocInfo datastructure that we use.

Since it's standardized I can lookup the DOI , convert it to CSL-JSON , and use the citation standards used in csl-json to allow people to convert the citations.

**Comment by thiswillbeyourgithub** [comment]
might as well post this here : 

there is a typo in the support section after paying a premium account : 
"As a premium user on the bronze you quali**F**y for premium support."
