### ISSUE TITLE
Paste from PDF into summernote form fails.

### ISSUE THREAD

**Issue by Lyroki17** [burtonator/polar-bookshelf#972]
copy from the PDF basically pastes 'nothing'.  I think the problem is it's pasting 'white' text into something that supports rich HTML.

I think what we could do is probably just fix the CSS properly or paste as text.

**Comment by burtonator** [comment]
What's the actual bug?  I think I know what you're talking about and it's already fixed in 1.19.4.

But if you could explain what's happening that would help.

**Comment by Lyroki17** [comment]
I can't copy an extract of the text (pdf) and paste in the comment (notes) or in the flashcards space. I have to type everything that I want. Hope you understand, thanks!

**Comment by burtonator** [comment]
You're right.  I'm going to rework this bug to make it a bit clear and will try to get it out into the next release.

For now you can KIND of get this functionality by doing "paste without formatting" from the menu bar.  But this shouldn't be required IMO.

**Comment by burtonator** [comment]
The HTML viewer is not impacted here.

**Comment by Lyroki17** [comment]
Yes, that's it. Thank you so much for the attention!

**Comment by burtonator** [comment]
here's how we have to handle this:

we register a window oncopy handler globally and just keep track of the 'last' copy from the clipboard.

Then, any copies done within polar directly are handled directly and reformatted to strip offending CSS styles.  Really we should have limited styles and possibly use the html cleanser component so that everything has a uniform look when pasted from within the app. (fonts , bold, italics, etc).

Anything EXTERNALLY should remain unmodified.
